server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cstju6pu0jms73aq5t5g-a.oregon-postgres.render.com:5432/banco
        username: banco_am5s_user
        password: EmTM9k8YhFxnXlZDI6EGR5hnFyLXqY8j
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            scheme-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres